### ISSUE TITLE
freshclam returns 1 on up-to-date, but man says 0

### ISSUE THREAD

**Issue by ctgraham** [clamwin/clamav#2]
Return codes in freshclam define a value of 0 for `FC_SUCCESS` and a value of 1 for `FC_UPTODATE`:
https://github.com/clamwin/clamav/blob/9309a7c0046585d05c20825b1d14de7fa3f93c01/freshclam/freshclamcodes.h#L24-L25
But the man page for freshclam says these are both 0:
https://github.com/clamwin/clamav/blob/8de125e48b51b691155a542ba0c25c4b9b9cb5e0/docs/man/freshclam.1.in#L100

The ability for freshclam to return 0 on `FC_SUCCESS` or `FC_UPTODATE` is highly desirable, for compatibility with tools like [cronic](https://habilis.net/cronic/), or [Windows-based scripted execution](https://github.com/clamwin/clamav-win32/issues/4).

I suspect this could be easily optionalized via a parallel to:
https://github.com/clamwin/clamav/blob/9309a7c0046585d05c20825b1d14de7fa3f93c01/shared/optparser.c#L486
and
https://github.com/clamwin/clamav/blob/9309a7c0046585d05c20825b1d14de7fa3f93c01/freshclam/manager.c#L2880-L2881
here:
https://github.com/clamwin/clamav/blob/9309a7c0046585d05c20825b1d14de7fa3f93c01/freshclam/manager.c#L2950

**Comment by sherpya** [comment]
looks like it does not need any changes now, freshclam will return 0 if retcode is <= 1

https://github.com/clamwin/clamav/blob/0.101.1/freshclam/freshclam.c#L761

**Comment by ctgraham** [comment]
Confirmed.  My installed version was 0.100.2 (epel's 0.100.2-1.el6).  This appears like it should be resolved in 0.101.1 and later.

**Comment by tech-dad** [comment]
I do not see version 101.1 available in epel-6. I do see

clamd-0.100.3-1.el6.x86_64

This still remains an issue in this version. This is causing our monitoring to fail, and does not allow us to update.

Thanks,
Zach
